spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: study
    password: study123
    schema: classpath:sql/schema.sql
    initialization-mode: always
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/study
    username: root
    password: 1234
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket