CREATE TABLE IF NOT EXISTS MESSAGES (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CONTENT varchar(300) NOT NULL,
  CONTENT_TYPE varchar(128) NOT NULL,
  SENT timestamp NOT NULL,
  USERNAME varchar(60) NOT NULL,
  USER_AVATAR_IMAGE_LINK varchar(256) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;